import { AIModelOption, AspectRatio, HistoryItem, PromptTemplate } from '@/types/ai-studio';

export const AVAILABLE_MODELS: AIModelOption[] = [
  {
    id: 'gpt-image-2',
    name: 'GPT Image 2',
    badge: '已接入',
    description: '由后台「系统连接配置」指定的 OpenAI 兼容生图模型，支持文生图与图生图编辑',
    creditsMultiplier: 1,
  },
];

export const ASPECT_RATIOS: { id: AspectRatio; label: string; iconRatio: string; desc: string }[] = [
  { id: 'auto', label: '自动', iconRatio: 'w-6 h-6 border-dashed', desc: '根据原图或提示自适应' },
  { id: '1:1', label: '1:1', iconRatio: 'w-6 h-6', desc: '正方形 · 头像/电商' },
  { id: '9:16', label: '9:16', iconRatio: 'w-4 h-7', desc: '竖屏全屏 · 故事/短视频' },
  { id: '16:9', label: '16:9', iconRatio: 'w-7 h-4', desc: '横屏宽屏 · 桌面壁纸/影视' },
  { id: '3:4', label: '3:4', iconRatio: 'w-5 h-7', desc: '经典竖幅 · 小红书/海报' },
  { id: '4:3', label: '4:3', iconRatio: 'w-7 h-5', desc: '经典横幅 · 展示图/摄影' },
  { id: '3:2', label: '3:2', iconRatio: 'w-6 h-4', desc: '单反相机画幅' },
  { id: '2:3', label: '2:3', iconRatio: 'w-4 h-6', desc: '经典胶片竖构图' },
  { id: '5:4', label: '5:4', iconRatio: 'w-6 h-5', desc: '大画幅艺术微喷' },
  { id: '4:5', label: '4:5', iconRatio: 'w-5 h-6', desc: '社交媒体标准竖图' },
  { id: '21:9', label: '21:9', iconRatio: 'w-8 h-3.5', desc: '超宽荧幕 · 电影级视觉' },
  { id: '1:4', label: '1:4', iconRatio: 'w-2.5 h-8', desc: '极窄竖条 · 卷轴/书签' },
  { id: '4:1', label: '4:1', iconRatio: 'w-8 h-2.5', desc: '极宽横条 · 网站通栏' },
  { id: '1:8', label: '1:8', iconRatio: 'w-1.5 h-8', desc: '超长竖幅' },
  { id: '8:1', label: '8:1', iconRatio: 'w-8 h-1.5', desc: '超长横幅' },
];

export const PROMPT_TEMPLATES: PromptTemplate[] = [
  {
    id: 'figure-model',
    title: '角色照片转手办模型',
    category: '手办/3D盲盒',
    prompt: '将这张照片转换为角色手办。在手办后面放一个印有角色形象的包装盒，旁边放一台电脑，屏幕上显示 Blender 建模过程。在包装盒前面放一个圆形塑料底座，角色手办站在上面。如果可能的话，场景设置在室内桌面。8k分辨率，真实环境光，微距镜头景深。',
    sampleOriginalImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    sampleImage: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80',
    defaultMode: 'image-edit',
    aspectRatio: '1:1',
    tags: ['手办', '3D模型', '桌面景深', '包装盒'],
  },
  {
    id: 'cyberpunk-neon',
    title: '未来赛博朋克雨夜街道',
    category: '概念艺术',
    prompt: '赛博朋克未来主义城市街景，下着细雨的夜晚，地面沥青有光泽的水坑反射着翠绿色#33fb02与电光紫霓虹招牌。高耸入云的摩天大楼带有全息投影，穿梭飞艇在雨雾中穿梭，电影级体积光与丁达尔效应，虚幻引擎5渲染质感，8K细节。',
    sampleImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
    defaultMode: 'text-to-image',
    aspectRatio: '16:9',
    tags: ['赛博朋克', '霓虹光', '超写实', '雨夜街景'],
  },
  {
    id: 'clay-world',
    title: '可爱粘土定格动画微缩屋',
    category: '3D/粘土',
    prompt: '可爱的手工黏土风格微缩房子，屋顶覆盖着小蘑菇和苔藓，门前有亮黄色的小灯和黏土小矮人。柔和的工作台摄影灯光，微微的黏土指纹质感，定格动画风格，倾斜移轴微距效果，高饱和度温馨色调。',
    sampleImage: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&auto=format&fit=crop&q=80',
    defaultMode: 'text-to-image',
    aspectRatio: '4:3',
    tags: ['粘土风格', '定格动画', '微缩模型', '温馨治愈'],
  },
  {
    id: 'commercial-product',
    title: '高端奢华香水商业海报',
    category: '商业产品',
    prompt: '极简高端玻璃香水瓶，放置在纯黑色磨砂玄武岩石板上，周围环绕着极光绿色彩烟雾与微小水滴飞溅。顶光与边缘轮廓光精准勾勒出香水瓶通透质感，极简奢华广告大片，哈苏中画幅相机拍摄，杂志封面级别。',
    sampleImage: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&auto=format&fit=crop&q=80',
    defaultMode: 'text-to-image',
    aspectRatio: '3:4',
    tags: ['商业摄影', '极简质感', '高端光影', '产品特写'],
  },
  {
    id: 'anime-mecha',
    title: '机甲少女战斗待机姿态',
    category: '二次元/原画',
    prompt: '日系顶级画师风格，未来机甲驾驶员少女，身穿半透明高科技动力装甲，荧光绿发光管线，银白色短发飘逸，眼神专注清澈。背景是格纳库整备平台与浮游炮单元，精细线稿，赛璐璐高光，色彩层次丰富，壁纸级精细度。',
    sampleImage: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
    defaultMode: 'text-to-image',
    aspectRatio: '9:16',
    tags: ['二次元', '机甲', '概念原画', '精细立绘'],
  },
  {
    id: 'photo-enhancement',
    title: '照片智能光影升级与艺术重绘',
    category: '图片编辑',
    prompt: '保持原图人物的脸部特征与姿态不变，将背景替换为极具科幻感的未来研究所，增加全身边缘发光的霓虹轮廓光，提升画质细节与皮肤质感，电影宽银幕色调。',
    sampleOriginalImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
    sampleImage: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80',
    defaultMode: 'image-edit',
    aspectRatio: '1:1',
    tags: ['照片重绘', '智能换背景', '光影修饰', '人物换装'],
  },
];

export const QUICK_PROMPT_TAGS = [
  '8K超清画质',
  '电影级体积光',
  '虚幻引擎5渲染',
  '哈苏微距摄影',
  '赛博朋克霓虹',
  '3D黏土盲盒',
  '极简商业美学',
  '柔和丁达尔光',
  '未来机甲科幻',
  '皮克斯3D动画风',
  '新海诚梦幻天空',
  '大师级手办质感',
];

export const INITIAL_HISTORY: HistoryItem[] = [
  {
    id: 'hist-sample-1',
    prompt: '将这张照片转换为角色手办。在手办后面放一个印有角色形象的包装盒，旁边放一台电脑，屏幕上显示 Blender 建模过程。在包装盒前面放一个圆形塑料底座，角色手办站在上面。如果可能的话，场景设置在室内桌面。',
    mode: 'image-edit',
    model: 'gpt-image-2',
    aspectRatio: '1:1',
    resolution: '1K',
    outputFormat: 'PNG',
    originalImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    resultImageUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80',
    timestamp: Date.now() - 1000 * 60 * 15,
    durationMs: 2350,
    seed: 884210,
    isFavorite: true,
  },
  {
    id: 'hist-sample-2',
    prompt: '赛博朋克未来主义城市街景，下着细雨的夜晚，地面沥青有光泽的水坑反射着翠绿色#33fb02与电光紫霓虹招牌。高耸入云的摩天大楼带有全息投影。',
    mode: 'text-to-image',
    model: 'gpt-image-2',
    aspectRatio: '16:9',
    resolution: '2K',
    outputFormat: 'PNG',
    resultImageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
    timestamp: Date.now() - 1000 * 60 * 65,
    durationMs: 3120,
    seed: 391822,
    isFavorite: false,
  },
  {
    id: 'hist-sample-3',
    prompt: '可爱的手工黏土风格微缩房子，屋顶覆盖着小蘑菇和苔藓，门前有亮黄色的小灯。',
    mode: 'text-to-image',
    model: 'gpt-image-2',
    aspectRatio: '4:3',
    resolution: '1K',
    outputFormat: 'PNG',
    resultImageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&auto=format&fit=crop&q=80',
    timestamp: Date.now() - 1000 * 60 * 180,
    durationMs: 1680,
    seed: 451920,
    isFavorite: true,
  },
];
